name: Trunk

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup LLVM toolchain
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "16.0"

      - name: Configure Release
        working-directory: ${{github.workspace}}
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Build Release
        working-directory: ${{github.workspace}}
        run: cd build && make filehash-test

      - name: Unit Test Release
        working-directory: ${{github.workspace}}
        run: cd build && filehash-test

      - name: Check formatting
        working-directory: ${{github.workspace}}
        run: clang-format --dry-run --Werror src/* test/*

      - name: Check codestyle
        working-directory: ${{github.workspace}}
        run: clang-tidy -p ./build/compile_commands.json test/*.cpp
