name: Trunk

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake -S . -B build && cmake --build build
